### ISSUE TITLE
Heads up, exception being thrown...

### ISSUE THREAD

**Issue by xorander00** [michaelestermann/WindowLayoutManager#12]
Great project man, much appreciated, keep it up! :)  I have a multi-monitor setup and your project saves me from having to spend a few minutes I open up a project in Android Studio.  
  
This is just a heads up for future reference.  I'm running the latest canary build of Android Studio, hence I expect stuff like this.  It worked fine up until the last couple of canary releases.
  
The plugin throws an exception when loading any project.  I haven't looked into it at all, but I'm assuming something changed in the Canary build that's incompatible with the plugin.  Maybe they removed something?  The exception is as follows...  
  
```
Unable to serialize Layout state

java.lang.NoSuchMethodError: java.util.List.toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object;
	at com.layoutmanager.persistence.LayoutConfig.getLayouts(LayoutConfig.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.serialization.PropertyAccessor.read(PropertyAccessor.java:51)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:32)
	at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:93)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:77)
	at com.intellij.serialization.xml.KotlinAwareBeanBinding.serializeInto(KotlinAwareBeanBinding.kt:38)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:67)
	at com.intellij.configurationStore.JdomSerializerImpl.serialize(xmlSerializer.kt:48)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:19)
	at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:18)
	at com.intellij.configurationStore.SaveSessionBaseKt.serializeState(SaveSessionBase.kt:46)
	at com.intellij.configurationStore.SaveSessionBase.setState(SaveSessionBase.kt:20)
	at com.intellij.configurationStore.ComponentStoreImpl.setStateToSaveSessionProducer(ComponentStoreImpl.kt:312)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:305)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:208)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:89)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponentsOnEdt$$inlined$withEdtContext$intellij_platform_configurationStore_impl$1.invokeSuspend(ComponentStoreImpl.kt:655)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at com.intellij.configurationStore.EdtPoolDispatcherManager.processQueue(EdtPoolDispatcher.kt:54)
	at com.intellij.configurationStore.EdtPoolDispatcherManager.access$processQueue(EdtPoolDispatcher.kt:18)
	at com.intellij.configurationStore.EdtPoolDispatcherManager$scheduleFlush$1.invoke(EdtPoolDispatcher.kt:32)
	at com.intellij.configurationStore.EdtPoolDispatcherManager$scheduleFlush$1.invoke(EdtPoolDispatcher.kt:18)
	at com.intellij.configurationStore.EdtPoolDispatcherKt$sam$java_lang_Runnable$0.run(EdtPoolDispatcher.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```  
  
If it's simply because of a change in the latest canary releases, no biggie.  If I get the chance, I'll look at the code and see if I can find the issue.

**Comment by xorander00** [comment]
Fixed.  I'm too lazy to clone the repo & submit a PR, but it's only changes to two lines...  
  
**src/main/java/com/layoutmanager/actions/LayoutCreator.java:48**:  
```toolWindows.toArray(ToolWindowInfo[]::new),```  
_...to..._
```toolWindows.stream().toArray(ToolWindowInfo[]::new),```  
  
**src/main/java/com/layoutmanager/persistence/LayoutConfig.java:42**:  
```return this.layouts.toArray(Layout[]::new);```  
_...to..._  
```return this.layouts.stream().toArray(Layout[]::new);```  
  
I haven't written any Java in a long time now, but apparently that conversion without the intermediate conversion to a stream is only supported on Java 11+, I think.  The compiler can't infer the type parameter without it.

**Comment by michaelestermann** [comment]
@xorander00 Thanks for the report and fix of the issue at the same time. Also glad to hear, that the plugins supports your work :)
I created a fixed version and it should be available within the next days after the jetbrains plugin verification.
Happy new year
