### ISSUE TITLE
Java exception, possibly corretto-related

### ISSUE THREAD

**Issue by Snaptags** [michaelestermann/WindowLayoutManager#13]
I installed the plugin into my WebStorm 2019.3.1 but only get Java exceptions. This may be related to the JDK version on my machine:
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
(Windows 10 64bit)

Should this plugin run using Corretto?

```
java.lang.NoSuchMethodError: java.util.List.toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object;
	at com.layoutmanager.persistence.LayoutConfig.getLayouts(LayoutConfig.java:42)
	at com.layoutmanager.cleanup.EmptyLayoutRemoverService.execute(EmptyLayoutRemoverService.java:11)
	at com.layoutmanager.startup.PluginBootstrapper.runActivity(PluginBootstrapper.java:14)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:216)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:177)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:396)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:388)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Snaptags** [comment]
Stupid me: https://github.com/michaelestermann/WindowLayoutManager/issues/12
