### ISSUE TITLE
Exception after update

### ISSUE THREAD

**Issue by Bonno** [michaelestermann/WindowLayoutManager#19]
Good day, tnx for the great plugin!
After the last update I run into exceptions when trying to restore my layouts. I make use of multiple screens with floating tool windows.

PhpStorm: 2019.3.1
Plugin version: 1.3.2

Any clue what can go wrong here?
Thanks in advance.

```
java.lang.NullPointerException
	at com.layoutmanager.ui.ToolWindowHelper.setBounds(ToolWindowHelper.java:29)
	at com.layoutmanager.actions.RestoreLayoutAction.applyToolWindowLayout(RestoreLayoutAction.java:76)
	at com.layoutmanager.actions.RestoreLayoutAction.applyLayout(RestoreLayoutAction.java:49)
	at com.layoutmanager.actions.RestoreLayoutAction.actionPerformed(RestoreLayoutAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:294)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:263)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by michaelestermann** [comment]
@Bonno I just downloaded Php Storm 2019.3.1 for windows and tested several layouts with different configurations (Docked, floating and windowed).
It looks like the Floating decorator is not set. This should be done by the IDE when setting the type of the toolwindow :/
You may share the layout.xml, its located in the configuration folder of your ide (On windows this would be C:\Users\%user%\.PhpStorm2019.3\config\options). Otherwise its hard to figure out, what the real issue is and its more like a guesswork. 
You may also try a fixed version for the latest eap 2020. You can download it and install it from your disk (Settings - plugin - install from disk) https://ci.appveyor.com/project/michaelestermann/windowlayoutmanager/build/artifacts

**Comment by Bonno** [comment]
@michaelestermann I think you were right about the decorator. I checked the layout.xml but couldn't see the problem at once. So I removed config/options/layout.xml, config/options/running.layout.xml and the config/workspace directory to start with a fresh default layout. After I rebuilded my own layout I could again store and apply them with your plugin. 

`<application>
  <component name="Layout">
    <option name="layouts">
      <array>
        <Layout>
          <option name="name" value="Dual screen" />
          <option name="toolWindows">
            <array>
              <ToolWindowInfo>
                <option name="anchor" value="left" />
                <option name="id" value="Favorites" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Services" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="3527" />
                    <option name="y" value="315" />
                    <option name="width" value="941" />
                    <option name="height" value="459" />
                  </Rectangle>
                </option>
                <option name="id" value="Find" />
                <option name="type" value="FLOATING" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Terminal" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="5748" />
                    <option name="y" value="648" />
                    <option name="width" value="1292" />
                    <option name="height" value="249" />
                  </Rectangle>
                </option>
                <option name="id" value="TODO" />
                <option name="type" value="FLOATING" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Event Log" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Database Changes" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="301" />
                    <option name="y" value="168" />
                    <option name="width" value="1897" />
                    <option name="height" value="1117" />
                  </Rectangle>
                </option>
                <option name="id" value="Version Control" />
                <option name="type" value="FLOATING" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="MagicentoScripts" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="4482" />
                    <option name="width" value="622" />
                    <option name="height" value="897" />
                  </Rectangle>
                </option>
                <option name="id" value="Project" />
                <option name="type" value="FLOATING" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="5104" />
                    <option name="width" value="643" />
                    <option name="height" value="897" />
                  </Rectangle>
                </option>
                <option name="id" value="Structure" />
                <option name="type" value="FLOATING" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="id" value="Database" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
            </array>
          </option>
        </Layout>
        <Layout>
          <option name="name" value="Single screen" />
          <option name="toolWindows">
            <array>
              <ToolWindowInfo>
                <option name="anchor" value="left" />
                <option name="id" value="Favorites" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Services" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Run" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Terminal" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Event Log" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="Database Changes" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="301" />
                    <option name="y" value="168" />
                    <option name="width" value="1897" />
                    <option name="height" value="1117" />
                  </Rectangle>
                </option>
                <option name="id" value="Version Control" />
                <option name="type" value="FLOATING" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="id" value="MagicentoScripts" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="628" />
                    <option name="width" value="1292" />
                    <option name="height" value="636" />
                  </Rectangle>
                </option>
                <option name="id" value="Find" />
                <option name="type" value="FLOATING" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="y" value="538" />
                    <option name="width" value="1920" />
                    <option name="height" value="494" />
                  </Rectangle>
                </option>
                <option name="id" value="Debug" />
                <option name="type" value="DOCKED" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="bottom" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="628" />
                    <option name="y" value="648" />
                    <option name="width" value="1292" />
                    <option name="height" value="249" />
                  </Rectangle>
                </option>
                <option name="id" value="TODO" />
                <option name="type" value="FLOATING" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="id" value="Database" />
                <option name="type" value="DOCKED" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="2560" />
                    <option name="y" value="118" />
                    <option name="width" value="383" />
                    <option name="height" value="911" />
                  </Rectangle>
                </option>
                <option name="id" value="Project" />
                <option name="type" value="DOCKED" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
              <ToolWindowInfo>
                <option name="anchor" value="right" />
                <option name="bounds">
                  <Rectangle>
                    <option name="x" value="2941" />
                    <option name="y" value="150" />
                    <option name="width" value="381" />
                    <option name="height" value="912" />
                  </Rectangle>
                </option>
                <option name="id" value="Structure" />
                <option name="type" value="DOCKED" />
                <option name="visible" value="true" />
              </ToolWindowInfo>
            </array>
          </option>
        </Layout>
      </array>
    </option>
  </component>
</application>`

**Comment by Bonno** [comment]
I can verify this solves the problem I encountered.

**Comment by michaelestermann** [comment]
Glad to hear that 👍
